services:
  - type: web
    name: telegram-clone-1
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://tilavovazizbek37_db_user:aevOGZSOsR80bbAO@cluster0.uzczovb.mongodb.net/telegram-clone?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: telegram-clone-secret-key-2024-render-production-super-secure
      - key: FRONTEND_URL
        value: https://telegram-clone-1.onrender.com